#!/bin/bash

DEVFOR_ROOT=$HOME/.devfor

mkdir -p $DEVFOR_ROOT && pushd $DEVFOR_ROOT

curl --remote-name https://raw.githubusercontent.com/nampdn/devfor/master/scripts/install.sh
curl --remote-name https://raw.githubusercontent.com/nampdn/devfor/master/presets/Brewfile

/usr/bin/env bash install.sh 2>&1 | tee ~/devfor.log

popd >/dev/null 2>&1