#!/bin/bash

DEVFOR_ROOT=$HOME/.devfor
REMOTE_REPO="https://raw.githubusercontent.com/nampdn/devfor/master"
REMOTE_SCRIPTS="$REMOTE_REPO/scripts"
REMOTE_PRESETS="$REMOTE_REPO/presets"

declare -a DOWNLOAD_SCRIPTS=(
    "$REMOTE_SCRIPTS/brew.sh"
    "$REMOTE_SCRIPTS/git.sh"
    "$REMOTE_SCRIPTS/install-linux.sh"
    "$REMOTE_SCRIPTS/install-mac.sh"
    "$REMOTE_SCRIPTS/nodejs.sh"
    "$REMOTE_SCRIPTS/ruby.sh"
    "$REMOTE_SCRIPTS/shell.sh"
    "$REMOTE_SCRIPTS/ssh.sh"
    "$REMOTE_SCRIPTS/utils.sh"
    "$REMOTE_SCRIPTS/font.sh"
    "$REMOTE_SCRIPTS/app.sh"
    "$REMOTE_SCRIPTS/mac.sh"
    "$REMOTE_PRESETS/Brewfile"
)

mkdir -p $DEVFOR_ROOT && pushd $DEVFOR_ROOT

# Download all required scripts
for i in "${DOWNLOAD_SCRIPTS[@]}"
do
    curl --remote-name "$i"
done

# Run specific OS
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    /usr/bin/env bash install-linux.sh 2>&1 | tee ~/devfor.log
elif [[ "$OSTYPE" == "darwin"* ]]; then
    /usr/bin/env bash install-mac.sh 2>&1 | tee ~/devfor.log
fi

popd >/dev/null 2>&1
